### ISSUE TITLE
[Bug]:  Name tag gets removed when joining a class

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you join a class other players name tags get removed, you can see an example in this video https://www.dropbox.com/s/0bb3gngfxkmshra/uQO4Huar3I.mp4?dl=0

### Expected Behavior

Name tags should not be removed when joining a class

### Steps To Reproduce

You need 2 accounts to see this happen. 

Join one account to a class, then while looking at that player join your other account to a class and you'll see the name tag of the other player get removed.

### Environment

```markdown
- Server Software: Paper
- ProSkillAPI Version: 1.1.7.3
- ProMCCore Version: 1.0.3.2
- Plugins: https://i.imgur.com/rhpcpDj.jpeg
```

**Comment by kylejolly** [comment]
A similar issue also happens with ```/scoreboard objective setdisplay belowName [name] ``` and ```/scoreboard objective setdisplay list [name]```. When the player does not have a class, the two scoreboard displays show. As soon as the player professes to a class, with the proskillapi sidebar enabled, those scoreboard displays disappear. If the proskillapi sidebar is disabled in config.yml, the normal functionality (without a class) resumes. This should be a bug since proskillapi only uses the "sidebar" display and should not be "locking out" the other scoreboard display types.

To reproduce:
1. Create a /scoreboard objective (can be dummy)
2. Set display for that objective to "belowName" or "list"
3. (optional) check to ensure objectives display on the player list or under player name
4. Profess into a proskillapi class (a different user does not need to)
5. The "belowName" and "list" displays disappear.

[https://discord.com/channels/818973833570680882/837842746587742228/916857039542702170]("list" display visible before professing class)
[https://discord.com/channels/818973833570680882/837842746587742228/916857113345671198]("belowName" display visible before professing class)
[https://discord.com/channels/818973833570680882/837842746587742228/916871463141781565](After professing class)

**Comment by Travja** [comment]
The problem here @kylejolly is that SkillAPI uses it's own Scoreboard, and players can only be part of a single scoreboard at a time. So when professing, they actually change scoreboards. The whole scoreboard functionality of the plugin will likely need to be redone to fix both of these issues. It'll need to be adapted so that it uses the existing scoreboard if one exists, otherwise it'll create a new one. I did make some adjustments so that the packet portion of scoreboards should be functioning properly now, however.

**Comment by Sentropic** [comment]
Can no longer replicate after the scoreboard fix in ProMCCore.
