### ISSUE TITLE
[Bug]: When the damage is checked with a damage display plugin, etc.  Damage that is not applied is displayed.

### ISSUE THREAD

**Issue by EyatMC** [promcteam/proskillapi#102]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/92635911/137589697-ef7721b6-c17b-4491-a06b-03e1b0c3b455.png)
![image](https://user-images.githubusercontent.com/92635911/137589704-f684968b-fe68-43db-980f-b7dca30810e9.png)
![image](https://user-images.githubusercontent.com/92635911/137589707-85779fc2-cacc-43ef-89f1-8084bfa272ff.png)

When the damage is checked with a damage display plugin, etc.  Damage that is not applied is displayed.

### Environment

```markdown
- Server Software: Paper
- ProSkillAPI Version: 1.1.7.3
- ProMCCore Version: 1.0.3.2
- Plugins: https://imgur.com/Kk0eZ9I
```

### Anything else?

related conversation

Spring******* : goflish, not sure is it related. This is an issue which I've said but not that important so I've ignored.
The particle projectile and targeter with similar mechanics seems to be using damage to detect entities. So even through the damage is not really damaging the entity, it will still trigger EntityDamageEvent. 
So when some plugins (like health indicator plugin), when their functions are listening to EntityDamageEvent,  they will be called even there is no incoming damages.

**Comment by goflishMC** [comment]
I tested this using the this skill: https://pastebin.com/mPjEyNQ6

I did this with and without holding an rpgitem while casting.

I did the cast with the /class cast command and got similar results.

When holding an item while casting (could be any item that has rpgitems phsyical damage on the item), I think it's doing the damage from the skillapi skill and whatever amount of physical damage is set to the item.

However, I did test this without holding an item and it still did multiple damage amounts.

In the following test: https://imgur.com/Z6oJPAH

I made a skillapi skill with no damage mechanic set in the skillapi class. When I cast using an ability trigger that i set to the item in rpgitems the particle projectile triggered damage on the other player based on the amount of physical damage that was on my item.

I'm not sure the best course of action to fix the issue when it's not intended to use the physical damage listed on the item.

One thought I had was to to put an option in the item generator to disable the extra damage that happens when the item is  not intended to be used as a "staff" or item that would cast a skill. 

This option would be set to false by default.
