### ISSUE TITLE
[Bug/Enhancement] Skill cannot be replaced while cooldown is in progress

### ISSUE THREAD

**Issue by EyatMC** [promcteam/proskillapi#152]
I hope you add these conditions to the config.

Do not allow input of "/class skill" command or change skills while the skill is on cooldown.

Let me show you an example of the current problem. If you used a skill with a 2 minute cooldown, you can replace it with another skill by entering "/class skill".

**Comment by Travja** [comment]
I'm going to go ahead and close this 1. because it's been a couple of years (oops..) and 2. because I don't really see this as a huge issue necessarily. If you want to penalize players for refunding a skill and reunlocking it immediately, set the Initialize trigger to trigger a proper cast and set the cooldown again there.
