### ISSUE TITLE
[Enhancement] Casting Rework

### ISSUE THREAD

**Issue by xPixelGeek** [promcteam/proskillapi#190]
**Is your feature request related to a problem? Please describe.**
The current casting design is sensitive and inconsistent, and doesn't satisfy the needs of all users.

**Describe the solution you'd like.**
Refer to my documentation here: https://docs.google.com/document/d/1POVtBTumyZI-tvsT1wNWeqh-J1_ovU03IfOi-Ef9Rec/edit?usp=sharing

**Describe alternatives you've considered.**
N/A

**Additional context.**
Per our conversations in our most recent Design Team meeting.

**Comment by RebelRanger** [comment]
Just something I'd like to add to this. When configured to allow players to set their own combos currently there's no way to "clear" their combo on the skill like you can do with binds.
For example if I set Fireball(which has no default combo) to LS L L L. And later I want to bind the skill to an item instead I'm still stuck with a combo on Fireball. I know I can change that combo but I can never clear the combo without resetting my data. 
Just thought I'd add this here instead of starting a new suggestion since it goes along with the casting stuff.

**Comment by goflishMC** [comment]
> **Is your feature request related to a problem? Please describe.** The current casting design is sensitive and inconsistent, and doesn't satisfy the needs of all users.
> 
> **Describe the solution you'd like.** Refer to my documentation here: https://docs.google.com/document/d/1POVtBTumyZI-tvsT1wNWeqh-J1_ovU03IfOi-Ef9Rec/edit?usp=sharing
> 
> **Describe alternatives you've considered.** N/A
> 
> **Additional context.** Per our conversations in our most recent Design Team meeting.

why did you delete this :(

This project is getting done soon.

**Comment by Travja** [comment]
Casting rework has been done.
