### ISSUE TITLE
[Bug]: Set 10 Heart Config Option

### ISSUE THREAD

**Issue by Svastojed** [promcteam/proskillapi#284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

When you  give a class 1 hp(half  a heart) to 18 hp(9 hearts) it shows 10 hearts with  the config option.

### Expected Behavior

Show half  a heart or 1 heart and so on for config old  hp option. correctly.

### Environment

```markdown
- Server Software:
- ProSkillAPI Version:
- ProMCCore Version:
- Plugins:
```

**Comment by lordsrubka5** [comment]
With the merge hearts option, health is no longer raw health. Each half a heart becomes 5% of the **MAX HEALTH** meaning that it will always display 10 hearts since you are on 100% max health regardless of it being 1/1 or 100/100 health

**Comment by Svastojed** [comment]
Yes  and thats really   confusing.

**Comment by lordsrubka5** [comment]
Most often people would replace those hearts with a some sort of an hp bar. It is a bit confusing in the start I agree, had people on my server create tickets very often asking why their hearts are no longer there but they got used to it over time. Its a good system compared to the alternative of having your screen covered up with hearts. If you do not plan to go into high health you can remove this but anything over ~60-80 health is a problem to have on the screen

**Comment by 3Lord3** [comment]
> Yes and thats really confusing.
You can change the display of hearts in config.yml
![image](https://user-images.githubusercontent.com/62335161/163549874-b279357f-162b-4f8e-a96e-0c75a464d7e5.png)

**Comment by Svastojed** [comment]
Yes i  am quite  aware  of the option  to disable/enable it.  however  as  rubska  said  he had  people  even  create  support tickets over it. this should be fixed.

**Comment by lordsrubka5** [comment]
There is nothing to be fixed though. They created tickets because we started using it mid way aka we weren't using it but decided to turn it on at a later state which a lot of people who aren't that knowledgeable in advanced stuff (and young players) didn't know what happened (It took us like a week or two to explain it to every player joining but after that no problems were asked about it, only couple people questioning why they take damage tick when they equip an item that has bonus health). The option is not a bug, it does what it says. Locks health bar to 10 hearts so it works as a bar. You don't see any other games change the length of the health bar depending on how much HP you have. They all have a same length bar but a number appears on top of it displaying raw health value

**Comment by Svastojed** [comment]
we need a  new   option  then.  all in all i am not  sure why you trying to prevent a  fix to this.

**Comment by lordsrubka5** [comment]
I'm all up for a new option if you think you need it. However I do not wish for old options to be changed if it is working as intended in the first place. I personally do not use max health under 20 so it does not affect me at all but some other people might be using it now or in the future.

Something like:

  # Whether to lock the health bar to 10 hearts
  # This does not affect total health, only the display
  old-health-bar: 'true' 
  # Should the health bar be downscaled to real health if the max is under 20?
  downscale-under: 'true'
  
Would get the job done

**Comment by Svastojed** [comment]
Sounds good to me.
