### ISSUE TITLE
[Bug]: Push mechanic sends diagonally

### ISSUE THREAD

**Issue by goflishMC** [promcteam/proskillapi#423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

When using the push mechanic with a high number like 75 pushes the player diagonally, instead of forward.

### Expected Behavior

When you use the push mechanic it should send them forward in the direction that you hit them with push.

### Steps To Reproduce

1. Make a push mechanic and set the speed to 75
2. Cast it on another player and it will send them diagonally

### Environment

```markdown
- Server Software: paper spigot 1.19.2
- ProSkillAPI Version: proskillapi-1.1.7.18-20221121.070512-25
- ProMCCore Version: promccore-1.0.3.10-20221127.174931-12
- Plugins: https://i.imgur.com/QITwbuK.png
```

**Comment by Travja** [comment]
In case anyone comes looking regarding this issue, here's a little more information on the subject. The push mechanic is more tailored for AOE-type effects where multiple targets are being pushed/pulled relative to the caster or a remembered location. Because of this, the direction the caster is looking, especially when considering a physical damage trigger, is irrelevant to the push. Thus, if the player you hit is slightly off to the side of you, they will get thrown seemingly diagonally.

If you would like to push/pull a player relative to where the caster is looking, use the Launch Mechanic with the Caster as the Relative.
