### ISSUE TITLE
[Enhancement] Signal mechanic and trigger

### ISSUE THREAD

**Issue by fructozer** [promcteam/proskillapi#520]
When a signal mechamic is called on a target, a signal trigger with a corresponding ID is triggered.
This will reduce repetition when creating skills. 
Example: Produces the same effect on targets dealing damage, taking damage, or moving
Now instead of duplicating blocks that obstruct the vision and repeating when there are changes, we can connect those 3 trigger mechanics to the same signal id

SignalTrigger:
- Mana: true/false
- Cooldown: true/false
- Caller Target: true/false  target to signal caller or caster
- Signal id: String

SignalMechanic:
- Signal id: String

**Comment by fructozer** [comment]
Simply put, I want to create a function that can be reused in the skill

**Comment by Travja** [comment]
I believe this would probably necessitate a larger refactor to allow truly transferable "functions", if you will. As a Signal Trigger, the trigger would exist within a skill, but would have to be one that is learned by the user in order to be used. If we expanded this out a little such that these Signals/Functions are accessible from any skill, they would probably end up in their own category and then be truly usable wherever with only the need to modify the single function.
