### ISSUE TITLE
[Enhancement] Attribute Requirements to unlock Skills

### ISSUE THREAD

**Issue by ton5040** [promcteam/proskillapi#529]
**Is your feature request related to a problem? Please describe.**
There's currently no way of making attribute requirements in order to learn skills, Example: Needing 30 Vitality in order to be able to spend points (from the first level) and to unlock this specific skill.

**Describe the solution you'd like**
Attribute requirements in order to learn skill

**Describe alternatives you've considered**
You could use a permission handler and use skills permissions alongside with the placeholders SkillApi gives you

**Additional context**
If this was to be implementated it would be nice if you could choose a list of attributes that [ ALL / ONLY ONE  ] needs to be high enough in order for you to learn that skill

thanks for the attention

**Comment by goflishMC** [comment]
On the skills details page add 2 new options that would require a certain attribute to unlock the skill
-Attribute Requirement
-Attribute Req Level

<pre>
Name:
Type:
Max Level:
#default false
#Attribute needed to be able to unlock this sklil
Attribute Requirement: <attribute>
#Level the attribute needs to be in order to unlock this skll
Attribute Req Level: <level>
</pre>
