### ISSUE TITLE
[Bug] Particles not showing up using a magma server

### ISSUE THREAD

**Issue by edgaradr223** [promcteam/proskillapi#75]
Skill particle effects are not showing up when casting spells on magma servers, tried with mohist server and had the same result, no console or error message, it just do the action with no animation, is it a bug or just an unsolvable issue with cauldron servers?

thank you.

**Comment by Travja** [comment]
What MC version are you running for Magma/Mohist? And do any of the particles work?

**Comment by edgaradr223** [comment]
Thank you for helping me Travja, Im running minecraft using 1.12.2 magma/mohist versions, tried almost every particle available in the editor but had no success they just dont show up; i asked the same question in magma's discord server and they said that this particular issue may be caused because particles in plugins need "reflection" to show up, and they said something about changing some lines in your dependency to make them work in cauldron servers,  i really dont understand what they mean im just less than a noob in coding but i wanted to know if this is a solvable bug or just one of these things you have to live with.

Thank you once again for your support.

**Comment by Travja** [comment]
We do not officially support 1.12. Some previous builds of the plugin may partially work with 1.12, but the latest builds shouldn't even really function with 1.12 to my understanding. The plugin actually still has scraps of code that support 1.8, though since we rely on ProMCCore for central functionality and it doesn't work on 1.12, much less anything older, we only officially support 1.16 and 1.17 at the moment. I will say that should you have it running well enough on 1.12, the 1.12 implementation of particles indeed does use Reflection and would likely need some modifications for Cauldron servers. 1.13 or newer actually uses the Spigot API to create and display particles.

All that being said, if updating to a newer version is not something you're able to do due to mods or otherwise, I'm not sure I can really be of much help. It's always sort of been at the back of our minds to one day re-implement support for 1.12. But _if_ that happens at all, it will be a long road before we get there. So the best thing I can do is encourage you to update to newer versions of the game.

**Comment by edgaradr223** [comment]
Alright i understand mate, im going to try and fix it by myself as somebody from magma discord apparently is going to tell me exactly what to do, if i have success ill let you know and give you a copy so if somebody like me comes with the same issue they would receive support on 1.12, keep doing what youre doing, dont let rpg die. Thank you.

**Comment by Travja** [comment]
You can also look at using mkcoldwolf's fork. https://github.com/mccwtech/SkillAPI-lts though I'm not sure that it would resolve your particle problems.

**Comment by edgaradr223** [comment]
oof dude, that fork absolutely fixed the issue with particles, thank you for your support
