### ISSUE TITLE
[Enhancement] Launch Mechanic

### ISSUE THREAD

**Issue by Rosash** [promcteam/proskillapi#86]
Is it possible to create a mechanic that moves you based on your camera movement?

So you move in the direction your camera is facing. Could be used for movement abilities such as flight, lunges, jumps, etc with more control.

**Comment by Sentropic** [comment]
There already is such mechanic

**Comment by lordsrubka5** [comment]
Except that the current ones work based on preset directions instead of angle.

Throw or whatever its called I forgot has a preset upwards backwards and sidways velocity. What we dont have is a velocity that changes based on the looking angle of the player meaning that if you look straight up you would get pulled straight upwards and of you look forwards ot would have no upwards speed. 

Technically possible with math but there isnt any sin and cos as a mechanic

**Comment by Sentropic** [comment]
I see. Perhaps the best approach to this would be an enhanced Push/Launch mechanic as in https://github.com/promcteam/proskillapi/issues/258. This would allow to launch the armor stand in custom directions, either relative with absolute values, or relative caster/target.
